
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.js'
export type * from './prismaNamespace.js'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Customer: 'Customer',
  Shift: 'Shift',
  Staff: 'Staff',
  Payment: 'Payment',
  Method: 'Method',
  Order: 'Order',
  Ticket: 'Ticket',
  Seat: 'Seat',
  Trip: 'Trip',
  SeatClass: 'SeatClass',
  Feedback: 'Feedback',
  Station: 'Station'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const CustomerScalarFieldEnum = {
  customerId: 'customerId',
  fullname: 'fullname',
  email: 'email',
  phone: 'phone',
  password: 'password',
  rank: 'rank',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CustomerScalarFieldEnum = (typeof CustomerScalarFieldEnum)[keyof typeof CustomerScalarFieldEnum]


export const ShiftScalarFieldEnum = {
  id: 'id',
  staffId: 'staffId',
  startTime: 'startTime',
  endTime: 'endTime'
} as const

export type ShiftScalarFieldEnum = (typeof ShiftScalarFieldEnum)[keyof typeof ShiftScalarFieldEnum]


export const StaffScalarFieldEnum = {
  staffId: 'staffId',
  fullname: 'fullname',
  email: 'email',
  phone: 'phone',
  password: 'password',
  role: 'role',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type StaffScalarFieldEnum = (typeof StaffScalarFieldEnum)[keyof typeof StaffScalarFieldEnum]


export const PaymentScalarFieldEnum = {
  paymentId: 'paymentId',
  orderId: 'orderId',
  methodId: 'methodId',
  price: 'price',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PaymentScalarFieldEnum = (typeof PaymentScalarFieldEnum)[keyof typeof PaymentScalarFieldEnum]


export const MethodScalarFieldEnum = {
  methodId: 'methodId',
  name: 'name',
  description: 'description'
} as const

export type MethodScalarFieldEnum = (typeof MethodScalarFieldEnum)[keyof typeof MethodScalarFieldEnum]


export const OrderScalarFieldEnum = {
  orderId: 'orderId',
  customerId: 'customerId',
  staffId: 'staffId',
  status: 'status',
  paymentId: 'paymentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type OrderScalarFieldEnum = (typeof OrderScalarFieldEnum)[keyof typeof OrderScalarFieldEnum]


export const TicketScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  passCCCD: 'passCCCD',
  passName: 'passName',
  status: 'status',
  seat_id: 'seat_id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TicketScalarFieldEnum = (typeof TicketScalarFieldEnum)[keyof typeof TicketScalarFieldEnum]


export const SeatScalarFieldEnum = {
  id: 'id',
  status: 'status',
  tripId: 'tripId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  seatClassId: 'seatClassId'
} as const

export type SeatScalarFieldEnum = (typeof SeatScalarFieldEnum)[keyof typeof SeatScalarFieldEnum]


export const TripScalarFieldEnum = {
  id: 'id',
  track: 'track',
  arrivalDate: 'arrivalDate'
} as const

export type TripScalarFieldEnum = (typeof TripScalarFieldEnum)[keyof typeof TripScalarFieldEnum]


export const SeatClassScalarFieldEnum = {
  id: 'id',
  name: 'name',
  price: 'price'
} as const

export type SeatClassScalarFieldEnum = (typeof SeatClassScalarFieldEnum)[keyof typeof SeatClassScalarFieldEnum]


export const FeedbackScalarFieldEnum = {
  id: 'id',
  customerId: 'customerId',
  content: 'content',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type FeedbackScalarFieldEnum = (typeof FeedbackScalarFieldEnum)[keyof typeof FeedbackScalarFieldEnum]


export const StationScalarFieldEnum = {
  stationId: 'stationId',
  name: 'name',
  location: 'location'
} as const

export type StationScalarFieldEnum = (typeof StationScalarFieldEnum)[keyof typeof StationScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

